chore(Makefile): updating echos and makefiles commands
reynan-dev/codenaute pull request #76
Opened 2023-06-16 13:36 UTC by reynan-dev

## Ticket

**Title:**
**Notion Link:**

## Description

- Updating Makefile's command to fit both docker compose versions
- Updating echos to explain what the command are doing.

## Guidelines

🔗 Link your PRs to their related Notion tickets
✍️ Use the commit convention to your pull request title
📃 If your code affects the build, update `README.md`
🚫 Do not merge a PR until all comments are resolved
🗑 Remove your branch after merging

2023-07-03 22:02 UTC, jkergal requested changes

2023-07-03 22:02 UTC, jkergal commented on Makefile
> +	@echo "Inizializate database with migrations"
```suggestion
	@echo "Initialize database with migrations"
```

2023-07-03 22:02 UTC, jkergal commented on Makefile
> +	@echo "Starting everyservices in quiet mode."
```suggestion
	@echo "Starting every services in quiet mode."
```

2023-07-03 22:02 UTC, jkergal commented on Makefile
> +	@echo "Stoping everyservices"
```suggestion
	@echo "Stoping every services"
```

2023-07-03 22:02 UTC, jkergal commented on database/Makefile
> +	@echo "Initializating database in quiet - Docker compose v1"
```suggestion
	@echo "Initializating database in quiet mode - Docker compose v1"
```

2023-07-16 07:58 UTC, reynan-dev commented on Makefile
> +	@echo "Inizializate database with migrations"
Done

2023-07-16 07:59 UTC, reynan-dev commented on Makefile
> +	@echo "Stoping everyservices"
Done

2023-07-16 07:59 UTC, reynan-dev commented on Makefile
> +	@echo "Starting everyservices in quiet mode."
Done

2023-07-16 07:59 UTC, reynan-dev commented on database/Makefile
> +	@echo "Initializating database in quiet - Docker compose v1"
Done

2023-07-21 08:17 UTC, jkergal approved these changes

2023-08-01 10:54 UTC, merged